### ISSUE TITLE
Data

### ISSUE THREAD

**Issue by KevinAquino** [neuroanatomy/34primates#1]
Hiya!

I was wondering if you going to release the data soon (or will wait for the manuscript to be accepted ?) really cool stuff!

**Comment by r03ert0** [comment]
hello! Yes, we were waiting for the acceptation... but there's maybe something among the https://braincatalogue.org/please data that you can use? Or were you looking for something in particular?

**Comment by KevinAquino** [comment]
Great! My main interest is looking at the surfaces for a project I will start later in the year. What is on the catalogue is great and will get me started ! :)
